version: "3.9"

services:
  db:
    container_name: shop-db
    image: postgres:15
    hostname: "psql_docker"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    networks:
      - postgres
    restart: always

  api:
    depends_on:
      - "db"
    container_name: shop-server
    build: .
    ports:
      - "8080:8080"
    networks:
      - postgres
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
